module.exports={"BookType":[
{"tag":"ancient_book","title":"古籍"},
{"tag":"art","title":"艺术"},
{"tag":"biography","title":"传记"},
{"tag":"computer_internet","title":"计算机/网络"},
{"tag":"culture","title":"文化"},
{"tag":"youth_literature","title":"青春文学"},
{"tag":"sucess_motivation","title":"成功/励志"},
{"tag":"psychology","title":"心理学"},
{"tag":"sexual_relations","title":"两性关系"},
{"tag":"social_sciences","title":"社会科学"},
{"tag":"tourist_map","title":"旅游/地图"},
{"tag":"cartoon_humor","title":"冷笑话"},
{"tag":"early_childhood_education","title":"育儿/早教"},
{"tag":"economy","title":"经济"},
{"tag":"build","title":"建筑"},
{"tag":"cooking_meals","title":"美食"},
{"tag":"factual_book","title":"人类故事"},
{"tag":"fashion_beauty","title":"时尚/美妆"},
{"tag":"geomantic_omen","title":"风水/占卜"},
{"tag":"handmade_diy","title":"手工/DIY"},
{"tag":"healthtips","title":"保健养生"},
{"tag":"Investment","title":"投资理财"},
{"tag":"law","title":"法律"},
{"tag":"leisure_hobby","title":"休闲/爱好"},
{"tag":"literature","title":"文学"},
{"tag":"manage","title":"管理"},
{"tag":"maternal_fetal_education","title":"孕产/胎教"},
{"tag":"novel","title":"小说"},
{"tag":"Parenting","title":"亲子/家教"},
{"tag":"philosophical_religion","title":"哲学/宗教"},
{"tag":"politics_military","title":"政治/军事"}],
"OptionShow":["disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree","disagree"],
  "BookNavigationUp": [
    { "url": 'functions/bookNavigateList?tag=art', "img": "../../img/icon/art.png", "text": '艺术' }, 
    { "url": 'functions/bookNavigateList?tag=biography', "img": "../../img/icon/history.png", "text": "传记" }, 
    { "url": 'functions/bookNavigateList?tag=economy', "img": "../../img/icon/economy.png", "text": '经济' }, 
    { "url": 'functions/bookNavigateList?tag=politics_military', "img": "../../img/icon/war.png", "text": '军事' }],
   "BookNavigationDown": [
     { "url": 'functions/bookNavigateList?tag=literature', "img": "../../img/icon/literature.png", "text": '文学' }, 
     { "url": 'functions/bookNavigateList?tag=healthtips', "img": "../../img/icon/medical.png", "text": '医学' }, 
     { "url": 'functions/bookNavigateList?tag=philosophical_religion', "img": "../../img/icon/philosophy.png", "text": '哲学' }, 
     { "url": 'functions/bookNavigateList?tag=sucess_motivation',"img": "../../img/icon/more.png","text": '更多'}],
   "BookAction":[{"bindtap":"relevant","name":"相关书","src":"../../img/icon/same.png"},{"bindtap":"bookOfLibrary","name":"馆藏情况","src":"../../img/icon/comment.png"},{"bindtap":"addBookToShelf","name":"收藏此书","src":"../../img/icon/read.png"}],"ReminderFunction":[{"title":"书籍到期提醒","warn":"开启后，在借阅书籍到期前一周会给您推送提醒还书"},{"title":"藏书到馆提醒","warn":"开启后，当预约图书到馆，会给您推送提醒"},{"title":"预约到期提醒","warn":"开启后，在预约期限前一星期，会给您推送提醒取书"}]
}